<a href="https://colab.research.google.com/github/sudemasali/AI-Bootcamp-Projects-/blob/main/ml_preprocessing_regression_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MACHINE LEARNING

In [ ]:
#Veri Ön İşleme Pratiği

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split #machine learning python kütüphanesi sklearn'dür
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
#StandartScaler ölçeklendirme için gerekli olan sınıf(standardisation)
#MinMaxScaler Normalizasyon için gerekli olan sınıf

In [4]:
df=pd.read_csv("musteri_verisi_ml_pratik.csv")
df.head()

    yas     maas     sehir         egitim  deneyim_yili satin_aldi
0  25.0  32000.0    Ankara         Lisans           1.0       Evet
1  31.0  41000.0  Istanbul  Yuksek Lisans           4.0      Hayir
2  28.0      NaN     Izmir         Lisans           2.0  Beklemede
3  45.0  67000.0    Ankara        Doktora          15.0      Hayir
4   NaN  52000.0     Bursa         Lisans           7.0       Evet

In [5]:
#missing value var mı bakıyoruz
df.isnull().sum()

yas             1
maas            1
sehir           0
egitim          1
deneyim_yili    1
satin_aldi      0
dtype: int64

In [6]:
#kayıp verileri dropna ile siliyoruz
df_dropna=df.dropna()
df_dropna

     yas     maas     sehir         egitim  deneyim_yili satin_aldi
0   25.0  32000.0    Ankara         Lisans           1.0       Evet
1   31.0  41000.0  Istanbul  Yuksek Lisans           4.0      Hayir
3   45.0  67000.0    Ankara        Doktora          15.0      Hayir
5   36.0  48000.0  Istanbul      On Lisans           6.0  Beklemede
7   41.0  61000.0    Ankara  Yuksek Lisans          11.0      Hayir
8   33.0  45000.0     Bursa         Lisans           5.0  Beklemede
10  38.0  56000.0     Izmir  Yuksek Lisans           9.0       Evet
11  30.0  43000.0    Ankara         Lisans           3.0  Beklemede

In [8]:
#sayısal sütunlardaki eksik verileri median ile doldurma
df_filled=df.copy()
sayisal_sutunlar=("yas","maas","deneyim_yili")

for sutun in sayisal_sutunlar:
  df_filled[sutun]=df_filled[sutun].fillna(df_filled[sutun].median())

In [11]:
#kategorik sütundaki eksik veriyi mod ile doldur
df_filled["egitim"] = df_filled["egitim"].fillna(df_filled["egitim"].mode()[0])
df_filled

     yas     maas     sehir         egitim  deneyim_yili satin_aldi
0   25.0  32000.0    Ankara         Lisans           1.0       Evet
1   31.0  41000.0  Istanbul  Yuksek Lisans           4.0      Hayir
2   28.0  45000.0     Izmir         Lisans           2.0  Beklemede
3   45.0  67000.0    Ankara        Doktora          15.0      Hayir
4   31.0  52000.0     Bursa         Lisans           7.0       Evet
5   36.0  48000.0  Istanbul      On Lisans           6.0  Beklemede
6   29.0  39000.0     Izmir         Lisans           5.0       Evet
7   41.0  61000.0    Ankara  Yuksek Lisans          11.0      Hayir
8   33.0  45000.0     Bursa         Lisans           5.0  Beklemede
9   27.0  35000.0  Istanbul         Lisans           2.0      Hayir
10  38.0  56000.0     Izmir  Yuksek Lisans           9.0       Evet
11  30.0  43000.0    Ankara         Lisans           3.0  Beklemede

In [13]:
#satın alıp almama bilgisini label encoding yapma
label_df = df_filled.copy()
label_encoder = LabelEncoder()
label_df["satin_aldi_bilgisi"] = label_encoder.fit_transform(label_df["satin_aldi"])
label_df

     yas     maas     sehir  ... deneyim_yili  satin_aldi satin_aldi_bilgisi
0   25.0  32000.0    Ankara  ...          1.0        Evet                  1
1   31.0  41000.0  Istanbul  ...          4.0       Hayir                  2
2   28.0  45000.0     Izmir  ...          2.0   Beklemede                  0
3   45.0  67000.0    Ankara  ...         15.0       Hayir                  2
4   31.0  52000.0     Bursa  ...          7.0        Evet                  1
5   36.0  48000.0  Istanbul  ...          6.0   Beklemede                  0
6   29.0  39000.0     Izmir  ...          5.0        Evet                  1
7   41.0  61000.0    Ankara  ...         11.0       Hayir                  2
8   33.0  45000.0     Bursa  ...          5.0   Beklemede                  0
9   27.0  35000.0  Istanbul  ...          2.0       Hayir                  2
10  38.0  56000.0     Izmir  ...          9.0        Evet                  1
11  30.0  43000.0    Ankara  ...          3.0   Beklemede                  0

[12 rows x 7 columns]

In [18]:
#satın alıp almama bilgisini One Hot Encoding yapma
onehot_target_df = pd.get_dummies(df_filled["satin_aldi"], prefix="satin_aldi") #burda sonuç ayrı bir df olarak tutuluyor
onehot_target_df

    satin_aldi_Beklemede  satin_aldi_Evet  satin_aldi_Hayir
0                  False             True             False
1                  False            False              True
2                   True            False             False
3                  False            False              True
4                  False             True             False
5                   True            False             False
6                  False             True             False
7                  False            False              True
8                   True            False             False
9                  False            False              True
10                 False             True             False
11                  True            False             False

In [20]:
#One Hot Encoding ve Label Encoding için farklı bir örnek
onehot_df = pd.get_dummies(df_filled, columns = ["egitim"], drop_first=True)  #df içindeki sütunları yerinde dönüştürüyor
onehot_df["satin_aldi"] = label_encoder.fit_transform(onehot_df["satin_aldi"])
onehot_df

     yas     maas  ... egitim_On Lisans  egitim_Yuksek Lisans
0   25.0  32000.0  ...            False                 False
1   31.0  41000.0  ...            False                  True
2   28.0  45000.0  ...            False                 False
3   45.0  67000.0  ...            False                 False
4   31.0  52000.0  ...            False                 False
5   36.0  48000.0  ...             True                 False
6   29.0  39000.0  ...            False                 False
7   41.0  61000.0  ...            False                  True
8   33.0  45000.0  ...            False                 False
9   27.0  35000.0  ...            False                 False
10  38.0  56000.0  ...            False                  True
11  30.0  43000.0  ...            False                 False

[12 rows x 8 columns]

In [23]:
#Standardizasyon ve Normalizasyona geçmek için elimizdeki veriyi x ve y şeklinde ikiye bölüyoruz
x = onehot_df.drop("satin_aldi" , axis=1) #features
y = onehot_df["satin_aldi"]  # target (satın alıp almama durumu) (tahmin etmek istediğimiz değer)

In [24]:
#yalnızca sayısal sütunlarda standardizasyon ve normalizasyon yapacağız
sayisal_ozellikler=["yas","maas","deneyim_yili"]

In [26]:
#standardizasyon(veriyi ortalaması 0 ve standart sapması 1 olacak şekilde dönüştürür)
X_standard = x.copy()
standard_scaler = StandardScaler()
X_standard[sayisal_ozellikler] = standard_scaler.fit_transform(X_standard[sayisal_ozellikler])
X_standard

         yas      maas  ... egitim_On Lisans  egitim_Yuksek Lisans
0  -1.357339 -1.502506  ...            False                 False
1  -0.317675 -0.601003  ...            False                  True
2  -0.837507 -0.200334  ...            False                 False
3   2.108207  2.003342  ...            False                 False
4  -0.317675  0.500835  ...            False                 False
5   0.548711  0.100167  ...             True                 False
6  -0.664230 -0.801337  ...            False                 False
7   1.415098  1.402339  ...            False                  True
8   0.028880 -0.200334  ...            False                 False
9  -1.010784 -1.202005  ...            False                 False
10  0.895266  0.901504  ...            False                  True
11 -0.490952 -0.400668  ...            False                 False

[12 rows x 7 columns]

In [27]:
#Normalizasyon (değerleri 0 ile 1 arasına sıkıştırır)
X_normalized = x.copy()
minmax_scaler = MinMaxScaler()
X_normalized[sayisal_ozellikler] = minmax_scaler.fit_transform(X_normalized[sayisal_ozellikler])
X_normalized

     yas      maas  ... egitim_On Lisans  egitim_Yuksek Lisans
0   0.00  0.000000  ...            False                 False
1   0.30  0.257143  ...            False                  True
2   0.15  0.371429  ...            False                 False
3   1.00  1.000000  ...            False                 False
4   0.30  0.571429  ...            False                 False
5   0.55  0.457143  ...             True                 False
6   0.20  0.200000  ...            False                 False
7   0.80  0.828571  ...            False                  True
8   0.40  0.371429  ...            False                 False
9   0.10  0.085714  ...            False                 False
10  0.65  0.685714  ...            False                  True
11  0.25  0.314286  ...            False                 False

[12 rows x 7 columns]

In [28]:
# Train test split ile veriyi eğitim ve test olarak ayıracağız
x_train, x_test, y_train, y_test = train_test_split(X_standard, y, test_size=0.2 , random_state=42)
print("x_train", x_train.shape)
print("x_test", x_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

x_train (9, 7)
x_test (3, 7)
y_train (9,)
y_test (3,)